### ISSUE TITLE
Meet a little problem

### ISSUE THREAD

**Issue by Gates2046** [bepu/bepuphysics2#75] opened 2019-07-03 02:40 UTC
Thanks for your great sharing, but I found I can't run Demos at first time. The Vs throw me this: "SharpDX.SharpDXException: 'HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.", when the code was running at this line: "vertexShader = new VertexShader(device, cache.GetShader($"{shaderPath}.vshader"));" in the file named RayTracedRenderer.cs.  I don't know the reason why, please help me if you are free. Thank you!

**Comment by RossNordby** [comment] 2019-07-03 18:06
Appears to be a duplicate of #68 

The demos application requires windows 7+ and a DX11 graphics capable graphics card. If you have that and are still unable to run the demos, please head over to #68 and try the instructions for using the debug layer.

Notably, the physics library itself does not have any dependency on graphics, so you should still be able to use it directly.

**Closed by RossNordby** 2019-07-03 18:06 UTC
